plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.compose)
    id 'kotlin-kapt'
    alias(libs.plugins.hilt.android)
}

android {
    namespace 'com.taller.motostock.feature.client'
    compileSdk 34

    defaultConfig {
        minSdk 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = '17'
                freeCompilerArgs += ["-Xexpect-actual-classes"]
            }
        }
    }
    iosX64 {
        binaries.framework {
            baseName = "FeatureClient"
            isStatic = true
        }
    }
    iosArm64 {
        binaries.framework {
            baseName = "FeatureClient"
            isStatic = true
        }
    }
    iosSimulatorArm64 {
        binaries.framework {
            baseName = "FeatureClient"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation project(':core:common')
                implementation project(':core:designsystem')
                implementation project(':core:domain')
                implementation compose.runtime
                implementation compose.foundation
                implementation compose.material3
                implementation compose.ui
            }
        }
        androidMain {
            dependencies {
                implementation libs.androidx.core.ktx
                implementation libs.hilt.android
                implementation libs.androidx.lifecycle.viewmodel.compose
                implementation libs.androidx.lifecycle.runtime.compose
                implementation libs.androidx.navigation.compose
                implementation libs.androidx.hilt.navigation.compose
            }
        }
        iosMain {
            dependencies {
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test')
            }
        }
    }
}

dependencies {
    kapt libs.hilt.compiler
}
