plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.compose)
}

android {
    namespace 'com.taller.motostock.core.designsystem'
    compileSdk 34

    defaultConfig {
        minSdk 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = '17'
                freeCompilerArgs += ["-Xexpect-actual-classes"]
            }
        }
    }
    iosX64 {
        binaries.framework {
            baseName = "DesignSystem"
            isStatic = true
        }
    }
    iosArm64 {
        binaries.framework {
            baseName = "DesignSystem"
            isStatic = true
        }
    }
    iosSimulatorArm64 {
        binaries.framework {
            baseName = "DesignSystem"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation compose.runtime
                implementation compose.foundation
                implementation compose.material3
                implementation compose.ui
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test')
            }
        }
        androidMain {
            dependencies {
                implementation libs.androidx.core.ktx
            }
        }
    }
}
